## Preprocessing Merged Dataset

### Import Dependencies

In [254]:
import pandas as pd
from IPython.display import Image
import re
import ast
import fractions
from fractions import Fraction

### Import dataset

In [255]:
# Load Dataset Allrecipes
food_df = pd.read_csv('Food_Dataset.csv', index_col=None)
food_df.head()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
0,15 Best Air Fryer Thanksgiving Recipes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.allrecipes.com/thmb/zNe_lQRZgjj1rS...,https://www.allrecipes.com/gallery/best-air-fr...
1,Air Fryer Turkey Breast,"{'quantity': '1', 'unit': 'tablespoon', 'name'...",NaN,263,0g,40g,10g,6,https://www.allrecipes.com/thmb/PaF8nNOY0bLCvo...,https://www.allrecipes.com/recipe/275372/air-f...
2,16 Quick-and-Easy Side Dish Recipes for the Ai...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.allrecipes.com/thmb/91y3R4leqrUtBV...,https://www.allrecipes.com/gallery/air-fryer-s...
3,Best Holiday Party Appetizers to Make in the A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://cdn.jwplayer.com/v2/media/rggkwMPu/pos...,https://www.allrecipes.com/article/best-holida...
4,Air Fryer Lemon Garlic Parmesan Chicken,"{'quantity': '1 1/2', 'unit': 'pounds', 'name'...",Gather all ingredients.. Preheat an air fryer ...,365,8g,46g,17g,4,https://www.allrecipes.com/thmb/5nJvgXENSeFx82...,https://www.allrecipes.com/air-fryer-lemon-gar...

In [256]:
food_df.describe()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,24162,23091,20595,22841,22818,22774,22619,22834,24018,24162
unique,19282,18327,17042,2870,902,746,721,201,19091,19317
top,Gnocchi,"{'quantity': '4', 'unit': '', 'name': 'apples ...","Gather the ingredients.. Place whitefish, sour...",'0',1g,3g,0g,4,https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thu...,https://www.allrecipes.com/recipe/17445/grille...
freq,9,9,8,88,415,1490,813,4794,10,9

### Remove NaN

In [257]:
# Count of NaN values in each column
nan_count = food_df.isna().sum()

# Print the count of NaN values
print("Count of NaN values in each column:")
print(nan_count)

Count of NaN values in each column:
name              0
ingredients    1071
steps          3567
calories       1321
carbs          1344
protein        1388
fat            1543
servings       1328
image_url       144
link              0
dtype: int64

In [258]:
# Drop rows with any NaN values
food_df = food_df.dropna()

# Display the cleaned DataFrame
print("DataFrame after dropping rows with NaN values:")
food_df.describe()

DataFrame after dropping rows with NaN values:

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,20060,20060,20060,20060,20060,20060,20060,20060,20060,20060
unique,16586,16599,16604,2821,893,736,708,196,16592,16605
top,Smoked Fish Dip,"{'quantity': '2', 'unit': 'cups', 'name': 'fla...","Gather the ingredients.. Place whitefish, sour...",'0',1g,3g,0g,4,https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thu...,https://www.allrecipes.com/recipe/45291/smoked...
freq,8,8,8,88,336,1295,719,4355,10,8

### Remove duplicate

In [259]:
# Print the sum of duplicate rows
duplicate_count = food_df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 3455

In [260]:
# Remove the duplicate rows
food_df= food_df.drop_duplicates()

# Display the cleaned DataFrame
print("\nDataFrame after removing duplicate rows:")
food_df.describe()

DataFrame after removing duplicate rows:

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,16605,16605,16605,16605,16605,16605,16605,16605,16605,16605
unique,16586,16599,16604,2821,893,736,708,196,16592,16605
top,Cajun Chicken and Sausage Gumbo,[],Pour the 1/2 cup of water or milk into a small...,'0',1g,3g,0g,4,https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thu...,https://www.taste.com.au/recipes/grilled-haris...
freq,2,4,2,88,256,1030,540,3712,4,1

### Clean '[]' ingridients

In [261]:
# Remove rows where 'ingredients' is '[]'
food_df = food_df[food_df['ingredients'] != '[]']

# Display the cleaned DataFrame
print("DataFrame after removing rows with '[]' in the 'ingredients' column:")
food_df.describe()

DataFrame after removing rows with '[]' in the 'ingredients' column:

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,16601,16601,16601,16601,16601,16601,16601,16601,16601,16601
unique,16582,16598,16600,2820,892,735,706,196,16588,16601
top,Cajun Chicken and Sausage Gumbo,"{'quantity': '6', 'unit': '', 'name': 'eggs'}",Pour the 1/2 cup of water or milk into a small...,'0',1g,3g,0g,4,https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thu...,https://www.taste.com.au/recipes/grilled-haris...
freq,2,2,2,88,256,1030,540,3711,4,1

### Lowercase all name

In [262]:
# Convert all food names to lowercase
food_df['name'] = food_df['name'].str.lower()

# Display the updated DataFrame
print("DataFrame after converting food names to lowercase:")
food_df.head()

DataFrame after converting food names to lowercase:

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
4,air fryer lemon garlic parmesan chicken,"{'quantity': '1 1/2', 'unit': 'pounds', 'name'...",Gather all ingredients.. Preheat an air fryer ...,365,8g,46g,17g,4,https://www.allrecipes.com/thmb/5nJvgXENSeFx82...,https://www.allrecipes.com/air-fryer-lemon-gar...
6,air fryer s’mores,"{'quantity': '1', 'unit': 'sleeve', 'name': 'g...",Preheat an air fryer to 380 degrees F (193 deg...,143,20g,2g,6g,10,https://www.allrecipes.com/thmb/_EDaiFt0gIGQOL...,https://www.allrecipes.com/air-fryer-s-mores-r...
7,air fryer baked yams,"{'quantity': '1', 'unit': None, 'name': 'yam'}...",Preheat an air fryer to 400 degrees F (200 deg...,283,62g,3g,3g,1,https://www.allrecipes.com/thmb/156WNgRfzvGn-s...,https://www.allrecipes.com/air-fryer-baked-yam...
8,lemon garlic butter chicken spiedini,"{'quantity': '1/2', 'unit': 'cup', 'name': 'ex...","Whisk together olive oil, wine, 2 tablespoons ...",636,21g,43g,41g,6,https://cdn.jwplayer.com/v2/media/ahbYMLcr/thu...,https://www.allrecipes.com/lemon-garlic-butter...
9,air fryer grilled pimento cheese,"{'quantity': '4', 'unit': 'slices', 'name': 'F...",Preheat the air fryer to 370 degrees F (188 de...,902,108g,29g,40g,2,https://www.allrecipes.com/thmb/cdL3DKZH3beUk5...,https://www.allrecipes.com/air-fryer-grilled-p...

### Remove duplicated recipe name

In [263]:
# Remove duplicate food names, keeping the first occurrence
food_df = food_df.drop_duplicates(subset='name', keep='first')

# Display the cleaned DataFrame
print("DataFrame after removing duplicate food names:")
food_df.describe()

DataFrame after removing duplicate food names:

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,16569,16569,16569,16569,16569,16569,16569,16569,16569,16569
unique,16569,16566,16568,2805,885,729,703,195,16557,16569
top,grilled harissa zucchini on tabbouleh,"{'quantity': '12', 'unit': '', 'name': 'eggs'}",Pour the 1/2 cup of water or milk into a small...,'0',1g,3g,0g,4,https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thu...,https://www.taste.com.au/recipes/grilled-haris...
freq,1,2,2,88,255,1030,540,3703,4,1

### Check top frequency image_url

In [264]:
# Getting the mode
mode_image_url = food_df['image_url'].mode()

# Get the frequency of the most common image_url
mode_count = food_df['image_url'].value_counts().iloc[0]

# Print the full mode and the frequency (mode number)
print("Full mode of image_url column:")
print(mode_image_url.iloc[0])

print("\nMode count (number of occurrences):")
print(mode_count)

Full mode of image_url column:
https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thumbnails/RflzUhLv.jpg

Mode count (number of occurrences):
4

In [265]:
# URL of the image
image_url = "https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thumbnails/RflzUhLv.jpg"

# Display the image
Image(url=image_url)

No need to remove duplicate image

### Splitting into 3 df for to transform each website dataset into a same format

In [266]:
# Ensure there are no leading or trailing spaces in the link column
food_df['link'] = food_df['link'].str.strip()

# Split the DataFrame based on the 'link' column
Allrecipe_df = food_df[food_df['link'].str.contains('https://www.allrecipes.com', na=False)]
BBC_df = food_df[food_df['link'].str.contains('https://www.bbcgoodfood.com', na=False)]
Taste_df = food_df[food_df['link'].str.contains('https://www.taste.com.au', na=False)]

# Reset the index
Allrecipe_df.reset_index(drop=True, inplace=True)
BBC_df.reset_index(drop=True, inplace=True)
Taste_df.reset_index(drop=True, inplace=True)

### Transform ALLrecipe dataset into a same format (We use ALLrecipe_df 's format as the model for ther 2 other website)

In [267]:
Allrecipe_df.head()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
0,air fryer lemon garlic parmesan chicken,"{'quantity': '1 1/2', 'unit': 'pounds', 'name'...",Gather all ingredients.. Preheat an air fryer ...,365,8g,46g,17g,4,https://www.allrecipes.com/thmb/5nJvgXENSeFx82...,https://www.allrecipes.com/air-fryer-lemon-gar...
1,air fryer s’mores,"{'quantity': '1', 'unit': 'sleeve', 'name': 'g...",Preheat an air fryer to 380 degrees F (193 deg...,143,20g,2g,6g,10,https://www.allrecipes.com/thmb/_EDaiFt0gIGQOL...,https://www.allrecipes.com/air-fryer-s-mores-r...
2,air fryer baked yams,"{'quantity': '1', 'unit': None, 'name': 'yam'}...",Preheat an air fryer to 400 degrees F (200 deg...,283,62g,3g,3g,1,https://www.allrecipes.com/thmb/156WNgRfzvGn-s...,https://www.allrecipes.com/air-fryer-baked-yam...
3,lemon garlic butter chicken spiedini,"{'quantity': '1/2', 'unit': 'cup', 'name': 'ex...","Whisk together olive oil, wine, 2 tablespoons ...",636,21g,43g,41g,6,https://cdn.jwplayer.com/v2/media/ahbYMLcr/thu...,https://www.allrecipes.com/lemon-garlic-butter...
4,air fryer grilled pimento cheese,"{'quantity': '4', 'unit': 'slices', 'name': 'F...",Preheat the air fryer to 370 degrees F (188 de...,902,108g,29g,40g,2,https://www.allrecipes.com/thmb/cdL3DKZH3beUk5...,https://www.allrecipes.com/air-fryer-grilled-p...

In [268]:
Allrecipe_df.describe()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,12685,12685,12685,12685,12685,12685,12685,12685,12685,12685
unique,12685,12682,12684,1058,174,105,112,76,12673,12685
top,zucchini plum bread,"{'quantity': '2 ¼', 'unit': 'cups', 'name': 'I...",Pour the 1/2 cup of water or milk into a small...,145,1g,3g,0g,8,https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thu...,https://www.allrecipes.com/recipe/234327/zucch...
freq,1,2,2,38,255,1030,540,2369,4,1

### Transform BBCGoodFood dataset into a same format

In [269]:
#Check what format we're dealing with
BBC_df.head()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
0,"('salsa verde baked eggs',)","([{'ingredient': 'olive oil', 'quantity': '5',...",(['Step 1: Drizzle 1 tbsp of the olive oil in ...,'268low','7g','12g','21g',4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/salsa-verd...
1,"('sausage & fennel orecchiette',)","([{'ingredient': '', 'quantity': '1', 'unit': ...","(['Step 1: Boil a large pan of salted water, t...",'527','62g','21g','19g',4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/sausage-fe...
2,"('roasted cod with zingy beetroot salad',)","([{'ingredient': 'baby new potatoes', 'quantit...",(['Step 1: Heat the oven to 200C/180C fan/gas ...,'262low','21g','36g','3glow',4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/roasted-co...
3,"('tomato soup & hummus crispbreads',)","([{'ingredient': 'rapeseed oil', 'quantity': '...",(['Step 1: Heat the oil in a large non-stick p...,'403','51g','15g','12g',4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/tomato-sou...
4,"('puy lentils with seared salmon',)","([{'ingredient': 'dried puy lentils', 'quantit...",(['Step 1: Put the lentils in a pan of water w...,'519','29g','38g','25g',2,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/puy-lentil...

In [270]:
BBC_df.describe()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,3065,3065,3065,3065,3065,3065,3065,3065,3065,3065
unique,3065,3065,3065,1003,178,179,151,168,3065,3065
top,"('cucumber & elderflower spritzer',)","([{'ingredient': '', 'quantity': '1', 'unit': ...",(['Step 1: Chop the cucumber into a few chunks...,'0','0g','2g','0g',4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/cucumber-e...
freq,1,1,1,88,110,195,182,877,1,1

In [271]:
# Function to clean up the columns
def clean_column(value):
    return value.strip("(['),]").replace("'", "").replace("low", "").strip()

# Apply the function to the relevant columns
BBC_df['name'] = BBC_df['name'].apply(clean_column)
BBC_df['ingredients'] = BBC_df['ingredients'].apply(lambda x: x.strip("(['),])"))
BBC_df['steps'] = BBC_df['steps'].apply(lambda x: x.strip("(['),])"))
BBC_df['calories'] = BBC_df['calories'].apply(clean_column)
BBC_df['carbs'] = BBC_df['carbs'].apply(clean_column)
BBC_df['protein'] = BBC_df['protein'].apply(clean_column)
BBC_df['fat'] = BBC_df['fat'].apply(clean_column)

C:\Users\johan\AppData\Local\Temp\ipykernel_15900\3217557777.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BBC_df['name'] = BBC_df['name'].apply(clean_column)
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\3217557777.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BBC_df['ingredients'] = BBC_df['ingredients'].apply(lambda x: x.strip("(['),])"))
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\3217557777.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BBC_df['steps'] = BBC_df['steps'].apply(lambda x: x.strip("(['),])"))
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\3217557777.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BBC_df['calories'] = BBC_df['calories'].apply(clean_column)
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\3217557777.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BBC_df['carbs'] = BBC_df['carbs'].apply(clean_column)
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\3217557777.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BBC_df['protein'] = BBC_df['protein'].apply(clean_column)
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\3217557777.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BBC_df['fat'] = BBC_df['fat'].apply(clean_column)

In [272]:
#Check result
BBC_df.head()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
0,salsa verde baked eggs,"{'ingredient': 'olive oil', 'quantity': '5', '...",Step 1: Drizzle 1 tbsp of the olive oil in afr...,268,7g,12g,21g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/salsa-verd...
1,sausage & fennel orecchiette,"{'ingredient': '', 'quantity': '1', 'unit': 'l...","Step 1: Boil a large pan of salted water, turn...",527,62g,21g,19g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/sausage-fe...
2,roasted cod with zingy beetroot salad,"{'ingredient': 'baby new potatoes', 'quantity'...",Step 1: Heat the oven to 200C/180C fan/gas 6. ...,262,21g,36g,3g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/roasted-co...
3,tomato soup & hummus crispbreads,"{'ingredient': 'rapeseed oil', 'quantity': '2'...",Step 1: Heat the oil in a large non-stick pan ...,403,51g,15g,12g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/tomato-sou...
4,puy lentils with seared salmon,"{'ingredient': 'dried puy lentils', 'quantity'...",Step 1: Put the lentils in a pan of water with...,519,29g,38g,25g,2,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/puy-lentil...

### Transform Taste dataset into a same format

In [273]:
def convert_to_decimal(quantity_str):
    """Convert a string representation of a number (including mixed numbers) to decimal."""
    if not quantity_str:
        return None
    
    # Clean up the string
    quantity_str = quantity_str.strip()
    
    try:
        # Check if it's a mixed number (e.g., "1 1/2")
        mixed_match = re.match(r'(\d+)\s+(\d+)/(\d+)', quantity_str)
        if mixed_match:
            whole = int(mixed_match.group(1))
            num = int(mixed_match.group(2))
            denom = int(mixed_match.group(3))
            return str(whole + (num / denom))
        
        # Check if it's a simple fraction (e.g., "1/2")
        fraction_match = re.match(r'(\d+)/(\d+)', quantity_str)
        if fraction_match:
            num = int(fraction_match.group(1))
            denom = int(fraction_match.group(2))
            return str(num / denom)
        
        # If it's a simple number, convert it directly
        return str(float(quantity_str))
    
    except (ValueError, ZeroDivisionError):
        return None

def parse_ingredient(ingredient):
    # Regex pattern to match quantity, unit, and name
    pattern = r'(?P<quantity>[0-9/.\s]+)?\s*(?P<unit>[a-zA-Z()]+)?\s*(?P<name>.+)'
    match = re.match(pattern, ingredient.strip())
    
    if match:
        # Get the initial groups
        quantity = match.group('quantity')
        unit = match.group('unit')
        name = match.group('name')
        
        # Clean up quantity and convert to decimal
        quantity = convert_to_decimal(quantity) if quantity else None
        
        # Clean up unit
        if unit:
            unit = standardize_unit(unit)
            # If unit is not valid, add it to the name
            if not unit and name:
                name = f"{match.group('unit')} {name}"
        
        # Clean up name:
        # 1. Remove content in parentheses
        name = re.sub(r'\([^)]*\)', '', name)
        
        # 2. Remove descriptive phrases after commas
        name = re.sub(r',.*$', '', name)

        # Remove all special symbols
        name = re.sub(r'[^a-zA-Z0-9\s]', '', name)
        
        # 3. Remove specific descriptors
        descriptors = [
            r'finely chopped',
            r'thinly sliced',
            r'peeled',
            r'seeded',
            r'\b\w+ly\b',  # words ending in 'ly',
            r'\b\w+ed\b',  # words ending in 'ed',
            # words about,
            r'about',
        ]
        for descriptor in descriptors:
            name = re.sub(descriptor, '', name, flags=re.IGNORECASE)
        
        # 4. Final cleanup
        name = name.strip(' ,')

        
        return {
            'quantity': quantity,
            'unit': unit,
            'name': name if name else ''
        }
    return None

In [274]:
# Fix unit to be valid
def standardize_unit(unit):
    """Standardize cooking units and validate them."""
    if not unit:
        return None
        
    # Dictionary of valid cooking units and their standard forms
    valid_units = {
        # Volume
        'tbsp': ['tbsp', 'tablespoon', 'tablespoons'],
        'tsp': ['tsp', 'teaspoon', 'teaspoons'],
        'cup': ['cup', 'cups', 'c'],
        'ml': ['ml', 'milliliter', 'milliliters', 'millilitre', 'millilitres'],
        'l': ['l', 'liter', 'liters', 'litre', 'litres'],
        
        # Weight
        'g': ['g', 'gram', 'grams'],
        'kg': ['kg', 'kilogram', 'kilograms'],
        'oz': ['oz', 'ounce', 'ounces'],
        'lb': ['lb', 'pound', 'pounds'],
        
        # Count
        'bunch': ['bunch', 'bunches'],
        'clove': ['clove', 'cloves'],
        'piece': ['piece', 'pieces']
    }
    
    # Convert to lowercase for comparison
    unit = unit.lower().strip()
    
    # Check if the unit is valid and return standardized form
    for standard, variants in valid_units.items():
        if unit in variants:
            return standard
            
    return None

In [275]:
# Function to extract the calorie value from the string
def extract_calories(energy_str):
    match = re.search(r'(\d+)\s*cal', energy_str)
    if match:
        return match.group(1)  # Extracts the calorie value
    # if energy_str is already a number return the number instead
    elif energy_str.isdigit():
        return energy_str
    return None

In [276]:
Taste_df = food_df[food_df['link'].str.contains('https://www.taste.com.au', na=False)]

In [277]:
# Safely handle the 'steps' column
if 'steps' in Taste_df.columns:
    Taste_df['steps'] = Taste_df['steps'].apply(
        lambda step_list: ', '.join(ast.literal_eval(step_list)) 
        if isinstance(step_list, str) and step_list.startswith('[') else step_list
    )

# Safely handle the 'ingredients' column
if 'ingredients' in Taste_df.columns:
    Taste_df['ingredients'] = Taste_df['ingredients'].apply(
        lambda ing_list: ', '.join(
            map(
                lambda item: str(parse_ingredient(item)) if parse_ingredient(item) else '',
                ast.literal_eval(ing_list)
            )
        ).strip('[]') 
        if isinstance(ing_list, str) and ing_list.startswith('[') else ing_list
    )

# Safely extract the calorie value from the 'calories'
def extract_calories(calorie_value):
    try:
        # Example: "300 kcal" -> "300"
        return int(re.search(r'\d+', calorie_value).group()) if isinstance(calorie_value, str) else None
    except (AttributeError, ValueError):
        return None

if 'calories' in Taste_df.columns:
    Taste_df['calories'] = Taste_df['calories'].apply(extract_calories)

Taste_df['ingredients']

C:\Users\johan\AppData\Local\Temp\ipykernel_15900\1505495725.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Taste_df['steps'] = Taste_df['steps'].apply(
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\1505495725.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Taste_df['ingredients'] = Taste_df['ingredients'].apply(
C:\Users\johan\AppData\Local\Temp\ipykernel_15900\1505495725.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Taste_df['calories'] = Taste_df['calories'].apply(extract_calories)

23316    {'quantity': '1.0', 'unit': 'cup', 'name': 'br...
23317    {'quantity': '1.0', 'unit': None, 'name': 'egg...
23318    {'quantity': '50.0', 'unit': 'g', 'name': 'Cha...
23319    {'quantity': '1.0', 'unit': 'tbsp', 'name': 'o...
23320    {'quantity': '1.0', 'unit': None, 'name': 'she...
                               ...
24157    {'quantity': '4.0', 'unit': None, 'name': 'sco...
24158    {'quantity': '3.0', 'unit': None, 'name': 'egg...
24159    {'quantity': '0.25', 'unit': 'cup', 'name': 'b...
24160    {'quantity': '100.0', 'unit': 'g', 'name': 'bu...
24161    {'quantity': '5.0', 'unit': None, 'name': 'zuc...
Name: ingredients, Length: 819, dtype: object

In [278]:
Taste_df.head()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
23316,easiest-ever fried rice,"{'quantity': '1.0', 'unit': 'cup', 'name': 'br...",Boil brown and white rice separately following...,2272,87.4g,26.8g,8.7g,4,https://content.api.news/v3/images/bin/640b903...,https://www.taste.com.au/recipes/unique-fried-...
23317,cheesy french onion meatballs and mushrooms,"{'quantity': '1.0', 'unit': None, 'name': 'egg...","Combine the egg, beef, breadcrumbs and 1&1/2 t...",3138,39.0g,35.9g,49.4g,4,https://img.taste.com.au/gJ9jKwKI/w720-h480-cf...,https://www.taste.com.au/recipes/cheesy-french...
23318,thai chicken lettuce cups with avocado and lime,"{'quantity': '50.0', 'unit': 'g', 'name': 'Cha...",Bring a large saucepan of salted water to a bo...,4775,80.9g,83.5g,56.8g,4,https://img.taste.com.au/fqti94HE/w720-h480-cf...,https://www.taste.com.au/recipes/thai-chicken-...
23319,oven-baked mushroom risotto with pesto,"{'quantity': '1.0', 'unit': 'tbsp', 'name': 'o...",Preheat oven to 150°C. Heat half the oil in a ...,2685,69.8g,15.2g,31.4g,6,https://img.taste.com.au/-botctrO/w720-h480-cf...,https://www.taste.com.au/recipes/oven-baked-mu...
23320,tomato-tofu salad with creamy ginger dressing,"{'quantity': '1.0', 'unit': None, 'name': 'she...",Preheat the oven to 220°C (200°C fan-forced). ...,1367,16.0g,8.1g,27.2g,4,https://img.taste.com.au/AWH3XZcf/w720-h480-cf...,https://www.taste.com.au/recipes/tomato-tofu-s...

### Merge back formated datasets

In [279]:
#Merge back
new_df = pd.concat([Allrecipe_df, BBC_df, Taste_df], ignore_index=True)

new_df.describe()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
count,16569,16569,16569,16569,16569,16569,16569,16569,16569,16569
unique,16515,16566,16568,1828,730,614,565,195,16557,16569
top,easy egg fried rice,"{'quantity': '12', 'unit': '', 'name': 'eggs'}",Pour the 1/2 cup of water or milk into a small...,0,3g,3g,0g,4,https://cdn.jwplayer.com/v2/media/Ug0PzrYB/thu...,https://www.taste.com.au/recipes/grilled-haris...
freq,2,2,2,88,330,1202,754,3703,4,1

### Standardize the metrics to gram and mililiters

In [280]:
import ast

# Conversion dictionary
CONVERSION_FACTORS = {
    'pounds': 453.592,
    'pound': 453.592,
    'ounces': 28.3495,
    'ounce': 28.3495,
    'grams': 1,
    'gram': 1,
    'g': 1,
    'ml': 1,
    'milliliters': 1,
    'l': 1000,
    'liters': 1000,
    'kilograms': 1000,
    'kilogram': 1000,
    'kg': 1000,
    'cups': 240,  # Assuming 1 cup = 240 ml
    'cup': 240,
    'tbsp': 15,
    'tablespoons': 15,
    'tablespoon': 15,
    'tsp': 5,
    'teaspoons': 5,
    'teaspoon': 5,
    'cloves': 5,  # Assuming 1 clove of garlic = 5 grams
    'large': 56.8
}

FRACTIONS = {
    '¼': '1/4',
    '½': '1/2',
    '⅓': '1/3',
    '¾': '3/4',
    '⅔': '2/3',
    '⅕': '1/5',
    '⅖': '2/5',
    '⅗': '3/5',
    '⅘': '4/5',
    '⅛': '1/8',
    '⅜': '3/8',
    '⅝': '5/8',
    '⅞': '7/8'
}

# Helper function to handle fractional quantities, including mixed fractions
import re

# Helper function to handle fractional quantities, including mixed fractions
def convert_to_number(quantity_str):
    try:
        quantity_str = re.sub(r'[\(\)-]', '', quantity_str)
        # Remove the unit (e.g., 'cup', 'tbsp', etc.)
        quantity_str = re.sub(r'\b(ppings of choice|cup|tsp|g|ml|ounce|gram|pound|cups|large|small|stick|tablespoon|tablespoons|Jamaican|lb|fluid|cans|whole|oven-ready)\b', '', quantity_str, flags=re.IGNORECASE).strip()
        
        match = re.match(r"^\s*(\d+(\.\d+)?)", quantity_str)
        if match:
            return float(match.group(1))
        
        # Check for empty or descriptive strings (like 'for serving' or 'to taste')
        if not quantity_str or 'for serving' in quantity_str.lower() or 'to taste' in quantity_str.lower():
            return None  # Return None to indicate this is not a valid quantity
        
        # Check if the quantity is zest
        if 'zest' in quantity_str.lower():
            return 5
        
        if 'chopped peanuts' in quantity_str.lower():
            return 132
        
        if 'baking spray' in quantity_str.lower():
            return None
        
        # Handle "plus" scenarios like "1/4 cup plus 1"
        if 'plus' in quantity_str:
            parts = quantity_str.split('plus')
            quantity_1 = convert_to_number(parts[0].strip())
            quantity_2 = convert_to_number(parts[1].strip())
            if quantity_1 is not None and quantity_2 is not None:
                return quantity_1 + quantity_2
            else:
                return None
        
        # Replace fractional symbols with standard fractions
        for symbol, fraction in FRACTIONS.items():
            if symbol in quantity_str:
                quantity_str = quantity_str.replace(symbol, fraction)
                
        # Handle ranges like "1 1/2 to 2" by taking the first value or averaging
        if 'to' in quantity_str:
            parts = quantity_str.split('to')
            lower = convert_to_number(parts[0].strip())
            upper = convert_to_number(parts[1].strip())
            if lower is not None and upper is not None:
                return (lower + upper) / 2  # or return lower, depending on your needs
            else:
                return None
        
        # Handle mixed fractions like "1 1/2"
        if ' ' in quantity_str:
            whole, fraction = quantity_str.split(' ')
            quantity = float(whole) + convert_to_number(fraction)
            return quantity
        
        # Handle standard fractions like "1/2"
        if '/' in quantity_str:
            numerator, denominator = quantity_str.split('/')
            quantity = float(numerator) / float(denominator)
            return quantity
        

        # Attempt to convert to a float
        try:
            quantity = float(quantity_str)
            return quantity
        except ValueError:
            return None  # Return None if the value cannot be converted
    except Exception as e:
        print(f"Error converting quantity: {quantity_str}")
        return None  # Return None in case of any other error

# Function to process an individual ingredient
def process_ingredient(ingredient):
    try:
        quantity = ingredient.get("quantity")
        unit = ingredient.get("unit")
        name = ingredient.get("name")
        
        # Convert quantity using the helper function
        if isinstance(quantity, str):
            quantity = convert_to_number(quantity)
        
        # If quantity is None or invalid, return ingredient as is
        if quantity is None:
            return ingredient
        
        # Convert to grams or ml using the conversion factor
        if unit in CONVERSION_FACTORS and quantity is not None:
            conversion_factor = CONVERSION_FACTORS[unit]
            quantity_in_grams_or_ml = round(quantity * conversion_factor, 2)
            # Normalize unit to 'grams' or 'ml'
            normalized_unit = "grams"
        else:
            # If no unit or quantity, return as is
            quantity_in_grams_or_ml = quantity
            normalized_unit = unit

        # Return updated ingredient
        return {
            "quantity": quantity_in_grams_or_ml,
            "unit": normalized_unit,
            "name": name
        }
    except Exception as e:
        return [] 


# Function to process a list of ingredients
def process_ingredients(ingredients_str):
    try:
        ingredients_list = ast.literal_eval(ingredients_str)  # Safely evaluate the list
        processed_ingredients = [process_ingredient(ing) for ing in ingredients_list]
        return processed_ingredients
    except Exception as e:
        print(f"Error processing ingredients: {ingredients_str}, Error: {e}")
        return ingredients_str

# Apply the conversion function to the DataFrame
new_df["ingredients"] = new_df["ingredients"].apply(process_ingredients)

# Display updated ingredients
print("Updated Ingredients:")
ingredients_full = new_df.loc[0, 'ingredients']  # Replace 0 with the desired row index

# Print the full content of the 'ingredients' column
print(ingredients_full)

Updated Ingredients:
[{'quantity': 453.59, 'unit': 'grams', 'name': 'skinless boneless chicken thighs'}, {'quantity': 15.0, 'unit': 'grams', 'name': 'garlic, minced'}, {'quantity': 5.0, 'unit': 'grams', 'name': 'lemon zest'}, {'quantity': 5.0, 'unit': 'grams', 'name': 'paprika'}, {'quantity': 5.0, 'unit': 'grams', 'name': 'dried oregano'}, {'quantity': 5.0, 'unit': 'grams', 'name': 'salt'}, {'quantity': 5.0, 'unit': 'grams', 'name': 'crushed red pepper'}, {'quantity': 240.0, 'unit': 'grams', 'name': 'grated parmesan cheese'}, {'quantity': 240.0, 'unit': 'grams', 'name': 'panko bread crumbs'}, {'quantity': None, 'unit': None, 'name': 'cooking spray'}]

In [281]:
# def is_invalid_recipe(ingredients):
#     return any(item['quantity'] is None or item['unit'] is None for item in ingredients)

# # Filter out invalid recipes
# new_df = new_df[~new_df['ingredients'].apply(is_invalid_recipe)]

In [282]:
bbc = new_df[new_df['link'].str.contains('https://www.bbcgoodfood.com', na=False)]
bbc.head()

,name,ingredients,steps,calories,carbs,protein,fat,servings,image_url,link
12685,salsa verde baked eggs,"[{'quantity': 75.0, 'unit': 'grams', 'name': N...",Step 1: Drizzle 1 tbsp of the olive oil in afr...,268,7g,12g,21g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/salsa-verd...
12686,sausage & fennel orecchiette,"[{'quantity': 1.0, 'unit': 'leek', 'name': Non...","Step 1: Boil a large pan of salted water, turn...",527,62g,21g,19g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/sausage-fe...
12687,roasted cod with zingy beetroot salad,"[{'quantity': 200.0, 'unit': 'grams', 'name': ...",Step 1: Heat the oven to 200C/180C fan/gas 6. ...,262,21g,36g,3g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/roasted-co...
12688,tomato soup & hummus crispbreads,"[{'quantity': 30.0, 'unit': 'grams', 'name': N...",Step 1: Heat the oil in a large non-stick pan ...,403,51g,15g,12g,4,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/tomato-sou...
12689,puy lentils with seared salmon,"[{'quantity': 160.0, 'unit': 'grams', 'name': ...",Step 1: Put the lentils in a pan of water with...,519,29g,38g,25g,2,https://images.immediate.co.uk/production/vola...,https://www.bbcgoodfood.com/recipes/puy-lentil...

### Like One hot Encoding

### Export to cleaned.csv

In [283]:
# # Save the DataFrame to a CSV file
new_df.to_csv('cleaned.csv', index=False)

# # Confirm the saving
print("DataFrame has been saved to 'cleaned.csv'")

DataFrame has been saved to 'cleaned.csv'